package com.aimcoder.retrofit_get;


import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * @author SHOHRAB
 * @date 17-Oct-19
 */
/**
 * For this JSON format: https://ifconfig.co/json
 * This POJO class is generated by www.jsonschema2pojo.org
 */
public class ServerResponse implements Serializable {

    @SerializedName("ip")
    private String ip;
    @SerializedName("ip_decimal")
    private Integer ipDecimal;
    @SerializedName("country")
    private String country;
    @SerializedName("country_iso")
    private String countryIso;
    @SerializedName("city")
    private String city;
    @SerializedName("asn_org")
    private String asn_org;

    public String getAsn_org() {
        return asn_org;
    }

    public void setAsn_org(String asn_org) {
        this.asn_org = asn_org;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Integer getIpDecimal() {
        return ipDecimal;
    }

    public void setIpDecimal(Integer ipDecimal) {
        this.ipDecimal = ipDecimal;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCountryIso() {
        return countryIso;
    }

    public void setCountryIso(String countryIso) {
        this.countryIso = countryIso;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
}